import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useCallback, useEffect, useRef, useState } from 'react'
import { GiHamburgerMenu } from 'react-icons/gi'
import {
  Button,
  Flex,
  IconButton,
  VStack,
  useDisclosure,
} from '@chakra-ui/react'
import ChatMessage from '../components/ChatMessage'
import MenuButton from '../components/MenuButton'
import ChatInput from '../components/ChatInput'
import useStorage from '../hooks/useStorage'

export default function Home() {
  const [input, setInput] = useState('')
  const [chatLog, setChatLog] = useState([
    {
      user: 'oldg-pt',
      message: 'Hello, how I can help you today?',
    },
  ])
  const { isOpen, onOpen, onClose } = useDisclosure()
  const btnRef = useRef(null)
  const [name, setName] = useState<string | null>('')
  const { empty } = useStorage('username')

  useEffect(() => {
    if (!empty) {
      setName(localStorage.getItem('username'))
    }
  }, [empty])

  const handleClearChat = useCallback(() => {
    setChatLog([
      {
        user: 'oldg-pt',
        message: 'Hello, how I can help you today?',
      },
    ])
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Flex
        direction='column'
        maxW='1200px'
        align='center'
        m='0 auto'
        p='0 10px'
        h='100vh'
      >
        <Flex
          position='fixed'
          align='center'
          justify='space-between'
          w='full'
          mb='50px'
          left='50%'
          transform='translate(-50%, 0)'
          maxW='1200px'
          bgColor='gray.600'
          p='10px'
          borderBottomRadius={8}
        >
          <Button onClick={handleClearChat}>New Chat</Button>

          <IconButton
            variant='outline'
            colorScheme='teal'
            aria-label='Send email'
            icon={<GiHamburgerMenu />}
            color='blue.400'
            ref={btnRef}
            onClick={onOpen}
          />
        </Flex>

        <Flex flexDirection='column' w='full' justify='end' h='100vh'>
          <VStack
            direction='column'
            align='left'
            spacing='10px'
            w='full'
            pt='70px'
            pb='50px'
          >
            {chatLog?.map((message, idx) => (
              <ChatMessage key={idx} {...message} />
            ))}
          </VStack>

          <ChatInput
            input={input}
            setInput={setInput}
            chatLog={chatLog}
            setChatLog={setChatLog}
            name={name}
          />
        </Flex>
      </Flex>

      <MenuButton
        isOpen={isOpen}
        onClose={onClose}
        btnRef={btnRef}
        username={name}
      />
    </>
  )
}
